Design leaderboar apge
alexandr-kazakov/20-businessmen-team-02 pull request #10
Opened 2022-12-01 12:52 UTC by readOnlyMode

### Какую задачу решаем
Сверстать страницу лидерборда

2022-12-01 14:56 UTC, Olegas requested changes

2022-12-01 14:56 UTC, Olegas commented on packages/client/src/pages/Leaderboard/components/LeaderCard/type.ts
> +export enum LeaderVarian {
Опечатка? Variant?

2022-12-01 14:56 UTC, Olegas commented on packages/client/src/pages/Leaderboard/components/RankCard/RankCard.tsx
> +export const RankCard: FC<RankCardProps> = ({ alias, scores, avatar, first_name, direction }: RankCardProps) => {
У вас есть карточка со статистикой пользователя. Логично сделать что бы она принимала один параметр - user с типом User. Пусть в User есть некоторые поля, которые тут не используются. Это не страшно. Но по бизнесу у вас карточка про пользователя. А раз так - пусть она принимает этого пользователя в один параметр. Так и типизовать проще.

2022-12-01 14:56 UTC, Olegas commented on packages/client/src/pages/Leaderboard/components/LeaderCard/LeaderCard.tsx
> +export const LeaderCard: FC<LeaderCardProps> = ({ name, scores, variant }: LeaderCardProps) => {
Карточка лидера. Принимает name, scores, variant. name и scores это точно свойства пользователя (User). Опять же по бизнесу - это карточка про пользователя у которой может быть разный вид, в зависимости от места на доске почета. Логично сделать два пропса:
1. user: User
2. variant: LeaderVariant

Пусть в user будут дополнительные поля, которые этой карточке не нужны - это не страшно.

2022-12-01 14:56 UTC, Olegas commented on packages/client/src/pages/Leaderboard/components/LeaderCard/LeaderCard.tsx
> +import { LeaderCardProps } from './type'
Предложение: хранить тип пропсов компонента в файле с компонентом. Так, например, выше сделано в WithRedirectTo. И это очень удобно потому что при чтении кода сразу видно что принимает компонент на вход, какого оно типа, что обязательное а что нет. Прыгать по файлам - долго и неудобно, сложнее изучать код.

2022-12-01 14:56 UTC, Olegas commented on packages/client/src/styles/mixins.scss
> +}
Миксины для повторяющегося кода - супер! 🔥

2022-12-01 14:56 UTC, Olegas commented on packages/client/src/pages/Leaderboard/type.ts
> +export interface User {
Тип User по идее у вас должен быть общим через все приложение - это один из основных бизнес-объектов. Его можно сложить куда-то на более высокий уровень

2022-12-01 17:01 UTC, opv1 approved these changes

2022-12-01 17:01 UTC, opv1 commented on packages/client/src/pages/Leaderboard/index.tsx
> +        {users.slice(3).map(user => (
здесь на всякий лучше сделать проверку на пустоту массива...а то может упасть в будущем

2022-12-02 19:54 UTC, alexandr-kazakov commented on packages/client/src/styles/mixins.scss
> +}
@Olegas как используется этот миксин?

2022-12-03 12:52 UTC, Olegas commented on packages/client/src/styles/mixins.scss
> +}
@alexandr-kazakov посмотри в этой ветке поиском по проекту строку align-flex-container - этот миксин добавляет правила, описанные в нем, в ту точку, где этот миксин вызывается. Позволяет не дублировать код

2022-12-05 07:17 UTC, Olegas commented on packages/client/src/pages/Leaderboard/components/LeaderCard/LeaderCard.tsx
> +        <img src={avatar ? avatar : '/avatar.svg'} alt="user"></img>
Можно короче: `variant || '/avatar.svg'`

2022-12-05 07:17 UTC, Olegas commented on packages/client/src/pages/Leaderboard/components/Leaders/Leaders.tsx
> +    avatar: firstUser.avatar ?? '',
Опечатка? secondUser?

2022-12-05 18:59 UTC, Olegas approved these changes

2022-12-05 21:59 UTC, merged