Task 46
alexandr-kazakov/20-businessmen-team-02 pull request #12
Opened 2022-12-02 17:39 UTC by alexandr-kazakov

### Какую задачу решаем
Сделана базовая разметка страницы профиля пользователя.

### Скриншоты/видяшка (если есть)
-
### TBD (если есть)
-

2022-12-02 18:30 UTC, Olegas requested changes

2022-12-02 18:30 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  &__iprofile_user_data_col_right {
iprofile - опечатка?

2022-12-02 18:30 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/test.scss
> +.profile_user_data {
А что это за файл? Кажется выше ровно такой же

2022-12-02 18:30 UTC, Olegas commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  return api.get('forum/')
Тот же URL что у форума? Опечатка?

2022-12-02 18:30 UTC, Olegas commented on packages/client/src/pages/Profile/types/index.ts
> +  phone: string
Это же тип для форума. Тут явно что-то недоделано?

2022-12-02 19:34 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  &__iprofile_user_data_col_right {
Да исправил, спасибо. Кстати вопрос здесь про классы и SCSS стили. Я хочу писать по БЭМ и пишу так https://github.com/alexandr-kazakov/20-businessmen-team-02/blob/1139ea8010265de19dbe7b392566db257008767f/packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx#L14 Но возникла проблема, что я не могу использовать дефис в названии классов. 

1/ Подскажи пжл хорошую практику, как писать дефисы в названии классов, желательно без сторонних либ для классов. 2/ А также хорошую практику как писать по БЭМ в реакт, дабы не дублировать название классов в HTML-тегах. 
Спасибо.

2022-12-02 19:38 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/test.scss
> +.profile_user_data {
Это тестовый файл со стилями, как говорит его название.

2022-12-02 19:39 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/types/index.ts
> +  phone: string
Почему для форума, это тип для данных пользователя. Это страница профиля пользователя и там будут отображаться эти данные.

2022-12-02 19:40 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  return api.get('forum/')
Дело в том что redux идет в 6 модуле, а сейчас пятый. Как мне кажется практика не соответствует теории в этом месте. Так что, что касаемо redux пожалуйста просто пиши сразу как надо сделать. Я это еще не изучал.

2022-12-02 20:02 UTC, alexandr-kazakov commented
> TBD (если есть)

@Olegas что такое TBD?

2022-12-02 20:04 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/test.scss
> +.profile_user_data {
удалил файл

2022-12-02 20:04 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  return api.get('forum/')
исправил

2022-12-03 09:13 UTC, Olegas commented
@alexandr-kazakov TBD = To Be Defined

2022-12-03 09:20 UTC, Olegas commented on packages/client/src/pages/Profile/types/index.ts
> +  phone: string
Кажется когда писал комментарий - было другое название. Видимо оно смутило. Но надо тогда в единственном числе назвать - ProfileType

2022-12-03 09:20 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +      {listProfile.length !== 0 ? (
Это нормально что мы тут только первый элемент выводим?

2022-12-03 09:20 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  &__iprofile_user_data_col_right {
Можно {styles["name-with-defise"]} вот так попробовать. Но при использовании CSS-модулей точно ли надо именовать строго по БЭМ? БЭМ давал возможность придумывать имена без пересечений, но при использовании CSS-модулей пересечения невозможны... Но я тут не настаиваю, тут на выбор команды. Мой личный выбор - благодаря CSS-модулям можно придумывать простые названия

2022-12-03 09:20 UTC, Olegas commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  return api.get('forum/')
Тут был вопрос в том что экшен назваывается "получить профиль" а URL на который мы делаем запрос - /forum. Выглядит как или URL не тот или экшен называется не так.

2022-12-03 10:23 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  &__iprofile_user_data_col_right {
Во-первых я привык писать по БЭМу, поэтому пока не планирую отказываться. Во вторых, хотя твой аргумент, насчет пересечений верен, но ты, как мне кажется, забываешь про структуру самого .scss файла. Если я пишу по БЭМ, то .scss  файл не является набором несвязанных между собой классов, а там есть четкая структура. Мало того, что в этом легче разобраться, так и этот код я смогу использовать в другом проекте, где например не будет реакт, но нужны будут аналогичные стили для кнопки.

<img width="340" alt="Снимок экрана 2022-12-03 в 13 22 58" src="https://user-images.githubusercontent.com/20513262/205436263-7d5b155e-2300-4026-91d7-c0ed6402bf93.png">


На скриншоте моем пример не идеальный конечно, так как я тогда еще не понял, как писать классы через дефисы.

2022-12-03 10:27 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  &__iprofile_user_data_col_right {
@Olegas можешь еще подсказать, есть ли и какая либа для реакт, что позволяет писать классы на html теги подобным образом?

`className={header._black-theme._scroolled}` 
и это должно превратиться в: 
`header header_black-theme header_scroolled` классы.



короче говоря, чтобы не дублировать родителя в названии класса каждый раз.

2022-12-03 10:38 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/types/index.ts
> +  phone: string
Эти данные, что ты видишь, это реальные данные из API практикума в первом модуле данного курса, там они также использовались на странице профиля пользователя.

А что касаемо названия переменной с типами, спасибо исправлено.

2022-12-03 10:40 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  &__iprofile_user_data_col_right {
Нет, такой не встречал

2022-12-03 10:43 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  &__iprofile_user_data_col_right {
> Во-первых я привык писать по БЭМу, поэтому пока не планирую отказываться. Во вторых, хотя твой аргумент, насчет пересечений верен, но ты, как мне кажется, забываешь про структуру самого .scss файла. Если я пишу по БЭМ, то .scss файл не является набором несвязанных между собой классов, а там есть четкая структура. Мало того, что в этом легче разобраться, так и этот код я смогу использовать в другом проекте, где например не будет реакт, но нужны будут аналогичные стили для кнопки.
> 
> <img alt="Снимок экрана 2022-12-03 в 13 22 58" width="340" src="https://user-images.githubusercontent.com/20513262/205436263-7d5b155e-2300-4026-91d7-c0ed6402bf93.png">
> 
> На скриншоте моем пример не идеальный конечно, так как я тогда еще не понял, как писать классы через дефисы.

У scss файла нет обязательной структуры. Его можно писать просто друг за другом правила. Структуру туда приносит разработчик. Если хочется БЭМ с дефисами - тогда ‘styles[“my-name”]’ решает

2022-12-03 10:51 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  return api.get('forum/')
Да, теперь кажется все исправлено здесь.

2022-12-03 11:00 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +      {listProfile.length !== 0 ? (
Да, пока это нормальным мне кажется. Объяснение этому следующее: я пока еще не знаю точно какие данные будут у пользователя, может придется в массиве передавать. Ну и пока я оставил массив с одним элементом в виде объекта с данными пользователя.

2022-12-03 12:43 UTC, Olegas commented
> > TBD = To Be Defined
> 
> @Olegas а что туда обычно записывается. Отвечай пожалуйста подробнее...

@alexandr-kazakov что бы ответить точнее - нужен контекст. Предположу что речь про аббревиатуру из сообщения к комиту. Тогда тут видимо это To Be Done - какие-то вещи, которые должны быть сделаны по задаче, но по какой-то причине не реализованы и разработчик отдельно это указывает.

2022-12-03 12:44 UTC, Olegas approved these changes

2022-12-03 14:33 UTC, merged