Task 67
alexandr-kazakov/20-businessmen-team-02 pull request #19
Opened 2022-12-11 19:46 UTC by Kocherg1n

### Рефакторинг

2022-12-13 08:47 UTC, opv1 approved these changes

2022-12-13 08:47 UTC, opv1 commented on packages/client/src/components/UI/Button/index.tsx
> +  variant?: 'primary' | 'secondary'
это точно зря, у нас есть типизация и лучше нам ее использовать

2022-12-13 08:47 UTC, opv1 commented on packages/client/src/components/UI/Button/index.tsx
> +    [styles.primary]: variant === 'primary',
тоже самое...зачем уходить в ручное прописывание

2022-12-13 08:47 UTC, opv1 commented on packages/client/src/pages/Auth/components/AuthSignin/index.tsx
> +  const [disabled, setDisabled] = useState(true)
зачем убрал у хука тип значения?)

2022-12-13 08:47 UTC, opv1 commented on packages/client/src/pages/Auth/components/AuthSignin/index.tsx
> +        <Button onClick={handlerToggle} variant="secondary">
тоже...зачем писать руками, всегда можно в этом ошибиться и если secondary нужно будет переименовать например в mySecondary, то придется лазить и везде менять

2022-12-13 09:30 UTC, Kocherg1n commented on packages/client/src/components/UI/Button/index.tsx
> +  variant?: 'primary' | 'secondary'
сейчас у кнопки 2 возможных состояния **primary/secondary**
**primary** - по умолчанию, то есть при использовании нам достаточно написать `<Button>Кнопка</Button>` (без обязательного variant как было ранее), + при такой типизации **variant?: 'primary' | 'secondary'** нам не надо тащить везде **ENUM** с неоднозначным названием **ButtonStyles** и подставлять в **variant** значения из **ButtonStyles**
ну и если обратить внимание на популярные либы компонентов например **mui** или **ant.design** то будет очевидно что енамы нам в нашей кнопке тоже не нужны 😁

2022-12-13 09:30 UTC, Kocherg1n commented on packages/client/src/components/UI/Button/index.tsx
> +    [styles.primary]: variant === 'primary',
коммент по кнопке выше

2022-12-13 09:30 UTC, Kocherg1n commented on packages/client/src/pages/Auth/components/AuthSignin/index.tsx
> +  const [disabled, setDisabled] = useState(true)
на мой взгляд тут излишне, **typescript** отлично выводит типы (https://www.typescriptlang.org/docs/handbook/type-inference.html) к тому же тут очевидно что тип **boolean** и по названию переменной **disabled** и по начальному значению в **useState(true)**

2022-12-13 09:30 UTC, Kocherg1n commented on packages/client/src/pages/Auth/components/AuthSignin/index.tsx
> +        <Button onClick={handlerToggle} variant="secondary">
тебе typescript проверяет значение (primary/secondary) как ты можешь ошибиться тебе сразу подсветит?

2022-12-13 18:05 UTC, Olegas commented on packages/client/src/components/Canvas/index.tsx
> +import type { Position, ImageObj, Props } from './types'
А расскажите, зачем везде явно указывать что импортируется тип?

2022-12-13 18:07 UTC, Olegas requested changes
Давайте обсудим - зачем отказываться от энамов?

2022-12-13 18:07 UTC, Olegas commented on packages/client/src/components/UI/Button/index.tsx
> +  variant?: 'primary' | 'secondary'
Сделать параметр опциональным - норм. Убирать энамы - спорная история. Для чего? Чем они мешают? Я знаю чем они помогают, а чем мешают - не знаю.

2022-12-13 18:17 UTC, Olegas commented on packages/client/src/pages/Auth/components/AuthSignin/index.tsx
> +  const [disabled, setDisabled] = useState(true)
Тут соглашусь, тип лишний, TS его отлично выводит из начального значения

2022-12-13 18:19 UTC, Olegas commented on packages/client/src/components/UI/Button/index.tsx
> +  variant?: 'primary' | 'secondary'
К слову - ant.design не самый лучший пример для подражания (по крайней мере v3)... Много мы с ним какишей покушали на одном из проектов...

2022-12-16 17:06 UTC, Kocherg1n commented on packages/client/src/components/Canvas/index.tsx
> +import type { Position, ImageObj, Props } from './types'
Это не обязательно, но кажется что удобно в пачке импортов сразу видеть где импортируются типы.

2022-12-16 17:09 UTC, Kocherg1n commented on packages/client/src/components/UI/Button/index.tsx
> +  variant?: 'primary' | 'secondary'
энамы убрал чтоб не таскать их везде где используется Button, и максимум сейчас что прийдется написать для кнопки это - <Button variant="secondary" />
а чем они помогают в кнопке где 2 пропа и один из них по дефолту? что бы secondary написать без ошибок?

2022-12-16 19:41 UTC, Olegas commented on packages/client/src/components/UI/Button/index.tsx
> +  variant?: 'primary' | 'secondary'
Enum помогает в дальнейшем рафакторить и искать использования по коду. Потому что просто строка "secondary" может быть где-то еще в приложении и означать что-то другое. Когда мы ищем значение энама - мы ищем именно его и ничего другого.
+ Это свобода рефакторить, давать любые значения самому энаму. 
На практике поддерживать энамы проще чем набор строковых констант.

2022-12-17 13:01 UTC, Kocherg1n commented on packages/client/src/components/UI/Button/index.tsx
> +  variant?: 'primary' | 'secondary'
добавил enum

2022-12-17 19:27 UTC, Olegas commented on packages/client/src/pages/Forum/index.tsx
> +const ForumPage: React.FC = () => (
А для чего такие изменения? Код был рабочий. Был короткий тип. Переделывается на длинный React.FC. Для чего?

2022-12-17 19:27 UTC, Olegas commented on packages/client/src/pages/Forum/index.tsx
> +const ForumPage: React.FC = () => (
Я в целом не против - но не очень понимаю в чем смысл

2022-12-18 12:26 UTC, Kocherg1n commented on packages/client/src/pages/Forum/index.tsx
> +const ForumPage: React.FC = () => (
Договорились явно импортировать из 'react' только сам React и хуки, остальное через dot notation от React. Соблюдая один стиль написания везде.

2022-12-18 18:28 UTC, Olegas approved these changes

2022-12-19 05:37 UTC, merged