Добавление страницы регистрации и входа
alexandr-kazakov/20-businessmen-team-02 pull request #2
Opened 2022-11-24 12:40 UTC by opv1

### Какую задачу решаем
Добавил страницу регистрации и входа
Добавлены пакеты
Добавлен роутинг
Добавлен шрифт и нормалайз

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-11-24 20:09 UTC, OlegLaskov approved these changes
Паша, ты - крут!

2022-11-25 09:55 UTC, Olegas requested changes

2022-11-25 09:55 UTC, Olegas commented on packages/client/src/pages/Auth/redux/authSlice.ts
> +      state.status = 'loading'
Если у статуса есть фиксированные значения - лучше создать под них enum. Это сильно упростит рефакторинг в дальнейшем и проверку кода на уровне TypeScript

2022-11-25 09:55 UTC, Olegas commented on packages/client/src/pages/Auth/redux/authSlice.ts
> +  isLoading: boolean
Судя по всему, этот флаг лишний. Ниже в pending-состоянии выставляется status = 'loading'

2022-11-25 09:55 UTC, Olegas commented on packages/client/src/app/api.ts
> +  userToken: <string | null>null,
Для чего поле с токеном экспортируется в составе публичного API модуля? Лучше инкапсулировать его, сложив в локальную переменную уровня модуля и изменять публичными методами типа уже имеющегося setUserToken

2022-11-25 09:55 UTC, Olegas commented on packages/client/src/app/redux/store.ts
> +export const createStore = () => {
Для чего экспортировать функцию createStore

2022-11-25 09:55 UTC, Olegas commented on packages/client/src/app/redux/store.ts
> +        serializableCheck: false,
Давайте не будем отключать проверку на сериализацию дабы в дальнейшем избежать проблем, например с SSR. При возникновении явных проблем и ошибок от этой проверки лучше явно здесь добавлять исключения снабжая их комментариями - зачем это исключение нужно и почему без него не обойтись.

2022-11-25 10:03 UTC, opv1 commented on packages/client/src/app/api.ts
> +// const { REACT_APP_API } = process.env
исправил это в следующем мр`е

2022-11-25 10:03 UTC, opv1 commented on packages/client/src/app/api.ts
> +// const getURL = (path: string) => `${REACT_APP_API}/${path}`
Во-первых тут реакт не видит почему-то переменные окуржения...и исправил это в следующем мр`е

2022-11-25 10:05 UTC, opv1 commented on packages/client/src/components/UI/Button/index.tsx
> +  customProp?: any
исправил это в следующем мр`е

2022-11-25 10:05 UTC, opv1 commented on packages/client/src/components/UI/Button/index.tsx
> +  const { customProp, children, ...buttonProps } = props
исправил это в следующем мр`е

2022-11-25 10:09 UTC, opv1 commented on packages/client/src/app/redux/store.ts
> +export const createStore = () => {
для теста

2022-11-25 10:10 UTC, readOnlyMode approved these changes

2022-11-25 10:10 UTC, opv1 commented on packages/client/src/app/redux/store.ts
> +        serializableCheck: false,
хорошо, исправил в следующем мр`е

2022-11-25 10:10 UTC, opv1 commented on packages/client/src/pages/Auth/redux/authSlice.ts
> +  isLoading: boolean
хорошо, исправил в следующем мр`е

2022-11-25 10:11 UTC, opv1 commented on packages/client/src/pages/Auth/redux/authSlice.ts
> +  isAuth: boolean
хорошо, исправил в следующем мр`е

2022-11-25 10:12 UTC, opv1 commented on packages/client/src/app/api.ts
> +      // console.info('[API] change token', getHeaders(token))
хорошо, исправил в следующем мр`е

2022-11-25 10:21 UTC, opv1 commented on packages/client/src/app/api.ts
> +  userToken: <string | null>null,
пока кстати не понятно, нужно ли вообще это) ответ от ручки регистрации приходит просто строкой "ок", без токена

2022-11-25 10:51 UTC, Olegas commented on packages/client/src/app/api.ts
> +  userToken: <string | null>null,
Ок, давай пока оставим это как есть.

2022-11-25 11:02 UTC, Olegas commented on packages/client/src/app/redux/store.ts
> +export const createStore = () => {
Извиняюсь, не увидел что в тесте оно импортируется.

2022-11-25 11:09 UTC, Olegas requested changes

2022-11-25 11:09 UTC, Olegas commented on packages/client/src/components/UI/Button/styles.module.scss
> +    padding: 10px;
Давай вынесем padding в общий класс button и будет огонь 🔥

2022-11-25 12:03 UTC, Olegas requested changes

2022-11-25 12:03 UTC, Olegas commented on packages/client/src/pages/Auth/redux/authSlice.ts
> +  status: string
Последний шаг внедрения enum - как и с variant у кнопки, сделать тут не string а StatusType

2022-11-25 12:44 UTC, Olegas approved these changes

2022-11-25 12:44 UTC, Olegas commented
Все умнички! 🚀

2022-11-25 13:34 UTC, merged