feat: добавлена fullscreen api
alexandr-kazakov/20-businessmen-team-02 pull request #20
Opened 2022-12-13 17:22 UTC by opv1

### Какую задачу решаем
Добавлена fullscreen api

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-13 18:14 UTC, Olegas requested changes

2022-12-13 18:14 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    pressedKey.clear()
Вы хотите сделать выход из полноэкранного режима по Ctrl+Q? Тогда проверяйте что нажата Q и при этом ctrlKey == true 
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey

2022-12-14 11:29 UTC, opv1 commented on packages/client/src/pages/Game/index.tsx
> +    pressedKey.clear()
Ведь проверка чуть выше, на 67 строке, если комбинация не верная, дальше не пойдет. Или обязательна такая проверка нужна? А так корректно в данном случае отрабатывает, если фуллскрина нет, он включится, иначе наоборот и все по комбинации кодов клавиш, ControlLeft и KeyQ

2022-12-14 11:43 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    pressedKey.clear()
Ну тут просто очень сложно и непонятно написано ) Есть способ прямее, без промежуточных хранилищ и переборов, в одно действие буквально.

2022-12-14 18:39 UTC, opv1 commented on packages/client/src/pages/Game/index.tsx
> +    pressedKey.clear()
так?)

2022-12-14 19:10 UTC, Olegas requested changes

2022-12-14 19:10 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +      document.removeEventListener('keydown', event => handlerKeyDown(event))
Вот тут ошибка. У вас получилось что вы подписываете одну функцию, а отписываете совсем другую (хоть она даже и выглядит как первая). Нужно подписывать и отписывать одну и ту же функцию, иначе отписка не сработает.

2022-12-14 20:30 UTC, opv1 commented on packages/client/src/pages/Game/index.tsx
> +      document.removeEventListener('keydown', event => handlerKeyDown(event))
даже не догадывался...поправил)

2022-12-15 08:00 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +  const handlerKeyDown = (event: any) => {
У event есть тип, его можно импортировать из react - KeyboardEvent

2022-12-15 08:00 UTC, Olegas approved these changes

2022-12-15 08:15 UTC, opv1 commented on packages/client/src/pages/Game/index.tsx
> +  const handlerKeyDown = (event: any) => {
да, но я не поборол это) когда ставлю этот тип, он ругается и я пробовал исправить, но это оказалось выше моих сил)

2022-12-15 08:40 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +  const handlerKeyDown = (event: any) => {
Да, все верно... Я ошибся, тут надо использовать просто KeyboardEvent (нативный, а не из React). Тогда все работает и не ругается. Оно и верно - мы же тут навешиваем событие нативными средствами а не средствами React - с чего бы нам брать тип обработчика оттуда?

2022-12-15 11:32 UTC, OlegLaskov approved these changes

2022-12-15 17:22 UTC, merged