feat: добавлена навигация
alexandr-kazakov/20-businessmen-team-02 pull request #21
Opened 2022-12-14 20:26 UTC by opv1

### Какую задачу решаем
Добавлена навигация

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-15 20:23 UTC, OlegLaskov commented on packages/client/src/pages/Auth/components/AuthSignup/index.tsx
>          history.push('/')
А здесь может лучше константу использовать из links?

2022-12-15 20:26 UTC, OlegLaskov approved these changes

2022-12-16 06:10 UTC, opv1 commented on packages/client/src/pages/Auth/components/AuthSignup/index.tsx
>          history.push('/')
поправил)

2022-12-16 17:55 UTC, Kocherg1n commented on packages/client/src/components/Navigation/index.tsx
> +          <NavLink
так как происходит мапинг, то лучше мемоизировать:
 
`const linkNodes =  useMemo(() => links.map(...), [...])`

2022-12-16 19:31 UTC, Olegas requested changes

2022-12-16 19:31 UTC, Olegas commented on packages/client/src/components/ClickOutside/index.tsx
> +export const ClickOutside: React.FC<IClickOutside> = ({ isActive, onClick, children }) => {
Задача понятна, но выбрано не правильное решение. Из-за того что вы накрыли все приложение оверлеем, вам пришлось вытаскивать меню из потока и делать его выше оверлея. 

Это решается проще.
В самом меню, в момент когда вы его показали, повесьте с помощью DOM API обработчик клика не document на фазе capture (т.е. вы его поямаете раньше всех, пока он еще не дойдет до элемента на который нажали).
Далее проверьте, что элемент, на который нажали, находится вне меню (также через DOM API)

Если кликнули НЕ внутри - скрыть меню. И не придется ничего накрывать и вытаскивать элементы из верстки

2022-12-17 17:17 UTC, opv1 commented on packages/client/src/components/Navigation/index.tsx
> +          <NavLink
поправил

2022-12-17 17:17 UTC, opv1 commented on packages/client/src/components/ClickOutside/index.tsx
> +export const ClickOutside: React.FC<IClickOutside> = ({ isActive, onClick, children }) => {
поправил

2022-12-17 19:30 UTC, Olegas commented on packages/client/src/components/Navigation/index.tsx
> +      document.addEventListener('click', handlerClick)
Тут все же правильнее сделать через capture-фазу. Потому что если на странице будет какой-то элемент, который обработает клик и прервет всплытие, то до документа не долетит и меню не закроется

2022-12-18 08:54 UTC, opv1 commented on packages/client/src/components/Navigation/index.tsx
> +      document.addEventListener('click', handlerClick)
поправил)

2022-12-18 18:27 UTC, Olegas commented on packages/client/src/components/Navigation/index.tsx
> +      document.addEventListener('click', handlerClick, true)
Отлично! Теперь железобетонно 👍

2022-12-18 18:27 UTC, Olegas approved these changes

2022-12-19 05:41 UTC, Kocherg1n approved these changes

2022-12-19 07:21 UTC, merged