feat: profile page add edit option
alexandr-kazakov/20-businessmen-team-02 pull request #32
Opened 2023-01-22 18:34 UTC by alexandr-kazakov

Добавлена возможность редактирования пользовательских данных на странице профиля.

2023-01-22 19:55 UTC, Olegas requested changes

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  }
Тут что-то с форматирование. Правило уехало целиком влево

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/SubmitButton/index.tsx
> +}
К этому компоненту добавлен пустой CSS-файл, который к тому же нигде не импортируется.

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/EditButton/index.tsx
> +}
К этому компоненту добавлен пустой CSS-файл, который к тому же нигде не импортируется.

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Для чего эта строка? Она отключает проверку для следующей строки, но на следующей строке нет хука

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> + // @ts-ignore: Unreachable code error
Зачем тут ts-ignore?

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +  Object.entries(userObj).map(([key, value]) => {
Если не предполагается ничего возвращать из map - лучше использовать forEach

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +              // @ts-ignore */}
Зачем тут ts-ignore?

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +      Object.entries(editeduserObj).map(([key, value]) => (
Лучше сделать маппировку - исходный ключ в данных (phone, email, ...) в значение текстовой метки (Телефон, Емайл, ....) и сразу здесь без промежуточной коллекции editeduserObj выводить через map

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  profilenView: boolean
Что такое profilen? Кажется тут опечатка, и должно быть profile?

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +      state.profilenView = !state.profilenView
Если это действие задумано переключать булевскую переменную в противоположное состояние, лучше использовать в названии toggle - так сразу будет понятно что происходит

2023-01-22 19:55 UTC, Olegas commented on packages/client/src/pages/Profile/index.tsx
> +    const first_name: string = target[0].value
Не лучше ли дать input'ам имена и обращаться по ним, чем по индексам? При текущем решении смена верстки формы приведет к неработоспособности кода отправки данных

2023-01-23 16:02 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/SubmitButton/index.tsx
> +}
Я знаю, файл добавил на будущее, как для компонента(типа шаблон, в каждом компоненте свой файл с стилями), пока он не используется, ок?

2023-01-23 16:02 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/EditButton/index.tsx
> +}
Я знаю, файл добавил на будущее, как для компонента(типа шаблон, в каждом компоненте свой файл с стилями), пока он не используется, ок?

2023-01-23 16:04 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +              // @ts-ignore */}
Некоторые ошибки тапйскрипта пытаюсь решить с помощью комментов, списываю это на то, что я еще только учусь и не требуется делать идеально... ок?

2023-01-23 16:07 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/index.tsx
> +    const first_name: string = target[0].value
К сожалению про имена я понял поздно, переделывать нет ресурсов(сил и времени), кажется, что сейчас работает, да я прекрасно понимаю, что по индексам так делать это плохая практика.

2023-01-23 16:17 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  profilenView: boolean
Да, там опечатка у меня, я посмотрел, если править, то там во всех файлах придется это править, также и например setProfilenView переменную. В целом считаю, что и так понятно, так что оставлю.

2023-01-23 16:25 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/SubmitButton/index.tsx
> +}
Хотя могу и удалить его, удалю.

2023-01-23 16:29 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +      Object.entries(editeduserObj).map(([key, value]) => (
Не знаю, что такое маппировка, разбираться пока времени нет, оставлю текущий вариант, он работает отлично, если ты не против.

2023-01-23 17:11 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/styles.module.scss
> +  }
Исправлено

2023-01-23 17:11 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/SubmitButton/index.tsx
> +}
Удалил

2023-01-23 17:11 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/EditButton/index.tsx
> +}
Удалил

2023-01-23 17:15 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> + // @ts-ignore: Unreachable code error
Иначе ниже там ошибку тайпскрипт будет показывать, иногда я обхожу ошибки тайпскрипта с помощью подобных комментов, по крайней мере пока учусь и не могу все сделать идеально.

2023-01-23 19:06 UTC, Olegas commented on packages/client/src/pages/Profile/index.tsx
> +    const first_name: string = target[0].value
А надо много ресурсов на переделку?

2023-01-23 19:08 UTC, Olegas commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  profilenView: boolean
Александр, я против. Починка этой опечатки в современное IDE занимает примерно 1 минуту. Такие маленькие допущения приводят в итоге проект в плохое состояние.

2023-01-23 19:10 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +              // @ts-ignore */}
Нет, так не ок. Сейчас лучший момент научиться делать правильно, научиться разбираться в чем причина ошибки и как ее правильно исправлять. Давай разберемся! Покажи в чем там ошибка? Приходи со скринами, давай разберемся и сделаем правильно.

2023-01-23 19:11 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> + // @ts-ignore: Unreachable code error
Так вот пока учишься и надо разобраться почему так и как сделать правильно.

2023-01-23 19:20 UTC, Olegas commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Тут беда в том, что отключения линтера в целом опасная затея и нужно понимать зачем это делается а конкретно этого правила - еще и опасная практика и может вести к сложноуловимым багам и неработоспособности приложения. Поэтому я всегда прошу явно указать в чем причина отключения такого правила. 

Я извлек код этого PR, убрал эти комментарии, и оказалось, что эти комментарии маскировали реальные проблемы. Так делать неправильно! Надо разбираться о чем нас тут хочет линтер предупредить и писать правильно.

2023-01-27 18:14 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/index.tsx
> +    const first_name: string = target[0].value
Достаточно требуется, на этой неделе например у меня почти ни минуты свободного времени. Этот PR который ты видишь, я на него потратил полный выходной день. А еще есть другие PR, еще много теории.

2023-01-27 18:19 UTC, Olegas commented on packages/client/src/pages/Profile/index.tsx
> +    const first_name: string = target[0].value
Я все понимаю, но в текущей реализации кроме стилевых замечаний есть и явные ошибки. Я не могу пропустить код с ошибками. Если где-то что-то не понятно - я готов помочь, можем обсудить в личке. Как вариант - может кто-то из команды сможет помочь подхватить исправление?

2023-01-29 10:12 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/index.tsx
> +    const first_name: string = target[0].value
Просто пришли мне код как нужно сделать или четкий совет как исправить. Советы общие, что-то то там не работает, мне не помогут.

2023-01-29 11:12 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Исправлено, комментарий нет.

2023-01-29 11:12 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> + // @ts-ignore: Unreachable code error
Исправлено, комментарий нет.

2023-01-29 11:13 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +              // @ts-ignore */}
Исправлено, комментарий нет.

2023-01-29 11:14 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +      Object.entries(editeduserObj).map(([key, value]) => (
Ошибки я готов править, стилистическую вкусовщину не буду, просто времени и нервов на это у меня нет. Закрыто.

2023-01-29 11:14 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/redux/profileSlice.ts
> +  profilenView: boolean
Исправлено.

2023-01-29 11:16 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/index.tsx
> +    const first_name: string = target[0].value
Еще раз подчеркиваю: ошибки я готов править. Я исправил все ошибки типов, удалил комментарии. Но это я править не буду, да, это не лучшее решение, по индексам записывать, но это рабочее решение. Воспринимай это как костыль, костыли есть и в коммерческих проектах, а в учебных они могут быть и подавно. Тема закрыта.

2023-01-29 11:25 UTC, alexandr-kazakov commented on packages/client/src/pages/Profile/components/ProfileUserDataList/index.tsx
> +  Object.entries(userObj).map(([key, value]) => {
Я решил использовать map, это не ошибка.

2023-01-29 11:26 UTC, Olegas approved these changes

2023-01-29 11:28 UTC, merged