Task 70 Snackbar
alexandr-kazakov/20-businessmen-team-02 pull request #33
Opened 2023-01-27 20:15 UTC by OlegLaskov

### Какую задачу решаем
Added Snackbar

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-01-28 12:36 UTC, Olegas requested changes

2023-01-28 12:36 UTC, Olegas commented on packages/client/src/components/Snackbar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Зачем здесь отключили правило? Если его вернуть на место - что идет не так?

2023-01-28 14:07 UTC, OlegLaskov commented on packages/client/src/components/Snackbar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Просит добавить handleTimeout. После добавления handleTimeout, просит useCallback на handleTimeout с [dispatch]
И после этих добавлений происходит зацикливание при работе

2023-01-29 11:35 UTC, Olegas commented on packages/client/src/components/Snackbar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Все верно. Вывод - надо как-то порефакторить код а не "заметать под ковер" ;)
Смотри, если ты не будешь делать отдельную функцию handleTimeout снаружи, а просто внесешь ее тело в useEffect - смысл не поменяется но пропадет внешняя зависимость от функции и от таймера т.к. ты его локализуешь внутри useEffect.

2023-01-29 13:53 UTC, OlegLaskov commented on packages/client/src/components/Snackbar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Спасибо! Исправил

2023-01-29 14:27 UTC, alexandr-kazakov approved these changes
Одобряю.

2023-01-29 14:40 UTC, Olegas approved these changes
👍

2023-01-29 15:45 UTC, merged