feat: форум
alexandr-kazakov/20-businessmen-team-02 pull request #38
Opened 2023-02-08 08:12 UTC by opv1

### Какую задачу решаем
API форума и форум на клиенте

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-08 19:10 UTC, Olegas requested changes

2023-02-08 19:10 UTC, Olegas commented on packages/server/models/reaction.ts
> +}
Судя по коду, у вас на одном комментарии от данного автора может быть только одна реакиця с данным эмодзи.
Если так, то вам нужен уникальный индекс из трех полей (id_author, id_comment, value)

2023-02-09 06:38 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumComment/styles.module.scss
> +em-emoji-picker {
А вот и нет) это библиотека дает такой тег

2023-02-09 06:38 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumCreate/index.tsx
> +      dispatch(setIsCreateTopic(false))
Поправил

2023-02-09 06:38 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumItem/index.tsx
> +      dispatch(setSelectedIdTopic(topic.id))
Поправил

2023-02-09 06:38 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumList/index.tsx
> +    }
Поправил

2023-02-09 06:39 UTC, opv1 commented on packages/server/models/reaction.ts
> +}
Ну да, так ведь и есть там

2023-02-09 19:18 UTC, Olegas requested changes

2023-02-09 19:18 UTC, Olegas commented on packages/client/src/pages/Forum/redux/forumSlice.ts
> +  dispatch(getTopics())
Тут проблема. Раньше у вас был await и вы дожидались когда сервер ответит. Теперь же вы по сути делаете два параллельных запроса. Не факт что сервер уже завершит создание когда вы к нему за списком придете

2023-02-09 19:18 UTC, Olegas commented on packages/client/src/pages/Forum/redux/forumSlice.ts
> +    builder.addCase(getTopics.pending, state => {
Тут получилось очень много повторяющегося кода. Посмотрите на https://redux-toolkit.js.org/api/matching-utilities#using-matchers-to-reduce-code-complexity-duplication-and-boilerplate - позволит сильно сократить дублирование

2023-02-11 06:51 UTC, Olegas approved these changes
🔥 супер!

2023-02-11 07:38 UTC, merged