Task 30 canvas
alexandr-kazakov/20-businessmen-team-02 pull request #4
Opened 2022-11-27 22:23 UTC by OlegLaskov

### Какую задачу решаем
Task-30: Представление игры
Task-7: Игровой движок

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-11-28 06:16 UTC, Olegas requested changes

2022-11-28 06:16 UTC, Olegas commented on packages/client/src/components/Canvas/index.tsx
> +const CANVAS_HEIGHT	= 644,
В данном PR код не отформатирован в соответствии с настройками prettier.
Прошу либо настроить prettier в IDE либо перед комитом выполнить `yarn format` для приведения форматирования к единому виду во всем проекте.

Также предлагаю сразу на уровне комита проверять код и запрещать комит если требования prettier нарушены - https://github.com/alexandr-kazakov/20-businessmen-team-02/pull/5

2022-11-28 18:35 UTC, OlegLaskov commented on packages/client/src/components/Canvas/index.tsx
> +const CANVAS_HEIGHT	= 644,
Отформатировал

2022-11-29 06:19 UTC, Olegas approved these changes

2022-11-29 06:19 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +      <h1 className={styles.congrat}>{header}</h1>
Совет: если заголовка нет (при scores < 0 header = null) можно вообще не рисовать h1 с текстом (пусть и пустым, но DOM-узел в дереве будет)

```
<>
      <div className={styles.container}>
        <CanvasComponent setScores={setScores} />
      </div>
     { header && <h1 className={styles.congrat}>{header}</h1> }
```

2022-11-29 06:19 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +  const [scores, setScores] = React.useState(-1)
Совет: что бы не повторять постоянно React в строках типа React.FC и React.useState можно импортировать эти вещи явно

```
import React, { FC, useState } from 'react'
```

И далее использовать без префикса
```
const GamePage: FC = () => {
```

2022-11-29 06:20 UTC, Olegas commented
Молодцы! 👍 Все супер! Есть два небольших совета, можно доработать позже

2022-11-29 07:09 UTC, OlegLaskov commented on packages/client/src/pages/Game/index.tsx
> +      <h1 className={styles.congrat}>{header}</h1>
Исправил

2022-11-29 07:09 UTC, OlegLaskov commented on packages/client/src/pages/Game/index.tsx
> +  const [scores, setScores] = React.useState(-1)
Исправил

2022-11-29 07:46 UTC, opv1 approved these changes

2022-11-29 08:57 UTC, merged