feat: xss
alexandr-kazakov/20-businessmen-team-02 pull request #43
Opened 2023-02-16 18:52 UTC by opv1

### Какую задачу решаем
XSS

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-17 15:27 UTC, Olegas commented on packages/client/src/pages/Auth/components/AuthSignin/index.tsx
> +    const sanitizeValues = purifyValues(values)
А что здесь очищается и для чего?

2023-02-17 15:27 UTC, Olegas commented on packages/client/src/pages/ChangePassword/index.tsx
> +        const { newPassword, oldPassword } = sanitizeValues
Для чего нужно чистить что-то в паролях?

2023-02-17 15:27 UTC, Olegas commented on packages/client/src/pages/Auth/components/AuthSignup/index.tsx
> +      const { email, login, first_name, second_name, phone, password } = sanitizeValues
Что здесь очищается и для чего? Ведь все эти значения будут просто в текстовых полях. Разве они выводятся как разметка?

2023-02-17 17:33 UTC, opv1 commented on packages/client/src/pages/Auth/components/AuthSignin/index.tsx
> +    const sanitizeValues = purifyValues(values)
Понял)

2023-02-17 17:44 UTC, Olegas requested changes
Я уже почти заапрувил и тут понял, почему мне не нравится идея санитайзинга данных "на вхоже".
Смотрите, если я соберу запрос руками, в котором подготовлю данные без санитайзинга и просто отправлю его сам, руками, без вашего приложения. Таким образом обойду санитизацию.
И все кто после меня пойдут читать сайт, получат работающую XSS.
Санитайзинг должен быть как можно ближе к точке использования данных. А сейчас получается он максимально далеко (в точке, где они рождаются). Да еще и обойти можно.

2023-02-17 18:03 UTC, opv1 commented
> Я уже почти заапрувил и тут понял, почему мне не нравится идея санитайзинга данных "на вхоже". Смотрите, если я соберу запрос руками, в котором подготовлю данные без санитайзинга и просто отправлю его сам, руками, без вашего приложения. Таким образом обойду санитизацию. И все кто после меня пойдут читать сайт, получат работающую XSS. Санитайзинг должен быть как можно ближе к точке использования данных. А сейчас получается он максимально далеко (в точке, где они рождаются). Да еще и обойти можно.

"если я соберу запрос руками" - ты имеешь в виду соберешь запрос с квери параметрами? Сами запросы санитайзить?

2023-02-17 18:08 UTC, opv1 commented
> Я уже почти заапрувил и тут понял, почему мне не нравится идея санитайзинга данных "на вхоже". Смотрите, если я соберу запрос руками, в котором подготовлю данные без санитайзинга и просто отправлю его сам, руками, без вашего приложения. Таким образом обойду санитизацию. И все кто после меня пойдут читать сайт, получат работающую XSS. Санитайзинг должен быть как можно ближе к точке использования данных. А сейчас получается он максимально далеко (в точке, где они рождаются). Да еще и обойти можно.

на сервере я использую мидлвар xssFilter

2023-02-17 18:45 UTC, Olegas commented
> "если я соберу запрос руками" - ты имеешь в виду соберешь запрос с квери параметрами? Сами запросы санитайзить?

Да, я просто в консоли напишу fetch и положу туда все что захочу. Санитайзить надо в точке вывода, там где ты точно знаешь, какой у тебя контекст. Просто текст или HTML.



> на сервере я использую мидлвар xssFilter

Если ты про helmet.xssFilter то к сожалению он ничего не делает кроме как отключает один устаревший заголовок который влияет на некоторые багливые браузеры. Сами инъекции он не чистит. Потому что только разработчик может четко знать где у него какие данные и что надо чистить и что нет.

И самое главное - знание это появляется только в точке вывода этих данных.

2023-02-18 13:05 UTC, opv1 commented
Добавил мидлвар валидатор

2023-02-19 16:59 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumComment/index.tsx
> +        <p className={styles.text}>{purify(comment.text)}</p>
Зачем здесь делать purify если это просто текстовая нода? Даже елси в ней прилетит HTML то мы просто его увидим как текст. React не будет его рендерить на разметку.

2023-02-19 17:00 UTC, Olegas commented on packages/client/src/pages/Auth/components/AuthSignup/index.tsx
> +      )
Зачем здесь делать purify? Какую задачу решает?

2023-02-19 17:00 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumItem/index.tsx
> +        <span className={styles.title}>{purify(topic.title)}</span>
Здесь тоже идет создание текстовой ноды. Разметка тут не будет отрендерена как HTML-ноды

2023-02-19 17:01 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumWindow/index.tsx
> +            <p className={styles.description}>{purify(selectedTopic.description)}</p>
И здесь

2023-02-19 17:06 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumComment/index.tsx
> +        <p className={styles.text}>{purify(comment.text)}</p>
Получается, если на клиенте не вставляется именно HTML-разметка, санитайзить прилетающие значения никаким образом не нужно?

2023-02-19 17:07 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumComment/index.tsx
> +        <p className={styles.text}>{purify(comment.text)}</p>
Именно. В этой точке - точно не нужно. Попробуйте сами - уберите всю санитизацию везде и в тексте комментария введите какоу-нибудь разметку, посмотрите что получится

2023-02-19 17:17 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumComment/index.tsx
> +        <p className={styles.text}>{purify(comment.text)}</p>
Поправил)

2023-02-19 19:07 UTC, Olegas approved these changes

2023-02-20 06:07 UTC, merged