Create 500 and 404 pages
alexandr-kazakov/20-businessmen-team-02 pull request #6
Opened 2022-11-29 06:44 UTC by readOnlyMode

2022-11-29 06:52 UTC, readOnlyMode commented
Добавлены страницы 404 и 500.

2022-11-29 07:46 UTC, opv1 approved these changes

2022-11-29 08:26 UTC, OlegLaskov commented on packages/client/src/pages/Error/index.tsx
> +export const ErrorPage = function (props: ErrorPageProps) {
Может здесь поставить тип "FC" (from React)? Как ты считаешь?

2022-11-29 08:28 UTC, OlegLaskov commented on packages/client/src/pages/Error/not-found/not-found.tsx
> +export const NotFoundPage = function () {
И здесь? (Может здесь поставить тип "FC" (from React)? Как ты считаешь?)

2022-11-29 08:32 UTC, OlegLaskov reviewed
Сделал комменты в двух местах, там, по-моему, нужно поставить типизацию. А то по-умолчанию там тип "any". Проверь, может где-то еще пропустил. А в остальном, по-моему, отлично!

2022-11-29 18:07 UTC, readOnlyMode commented on packages/client/src/pages/Error/index.tsx
> +export const ErrorPage = function (props: ErrorPageProps) {
Поправил.

2022-11-29 18:08 UTC, readOnlyMode commented on packages/client/src/pages/Error/not-found/not-found.tsx
> +export const NotFoundPage = function () {
Поправил. Я за однобразие и за типизацию, так что согласен.

2022-11-30 04:32 UTC, Olegas requested changes

2022-11-30 04:32 UTC, Olegas commented on packages/client/src/pages/Error/unavailable/unavailable.tsx
> +import React from 'react'
Вижу у вас неконсистентность в именовании и обустройстве компонентов. 
Файлы (или папки) с компонентами где-то названы с большой буквы, а где-то с маленькой (unavailable и App). Где-то используется CamelCase (SignUp) а где-то kebab-case (not-found).

Про выделение папок для компонентов. Если сделали папку для компонента, по идее в папке нужно сделать index.ts и в нем экспортировать то, что является "публичным API" этого "модуля". Для одного компонента делать папку кажется излишним (конечно же если там больше ничего нет внутри, например стилей или тестов), т.е. тот же not-found и unavailable можно было сделать отдельными файлами прямо в pages/Error.

По поводу экспорта. pages/Error это "модуль" который экспортирует то, что должно использоваться публично. Для приложения в целом тут важны компоненты not-found и unavailable, именно они и должны быть экспортированы из индексного файла. А компонент ErrorPage не должен вылезать наружу из этой библиотеки, это внутренняя (для модуля) штука, которая нужна для устранения дублирвоания кода (круто, кстати, что выделили такой компонент, молодцы 👍).

Итого, как я вижу структуру на пример данного модуля
```
pages/Error
-- index.tx (тут только экспорты NotFound и Unavailable)
-- NotFound.tsx (компонент NotFound)
-- Unavailable.tsx (компонент Unavailable)
-- ErrorPage.tsx (компонент ErrorPage)
-- ErrorPage.test.tsx (тесты)
-- styles.module.scss
-- types.ts
```

2022-11-30 04:32 UTC, Olegas commented on packages/client/src/pages/Error/styles.module.scss
> +  & .code {
Вы используете CSS-модули (круто что сразу их принесли 🔥) а зачем тогда в CSS каскады? Зачем делать вложенность `.container .code`?

2022-11-30 04:32 UTC, Olegas commented on packages/client/src/pages/Error/index.tsx
> +export const ErrorPage: React.FC<ErrorPageProps> = (props: ErrorPageProps) => {
Круто что выделили базовый компонент, молодцы! 👍

2022-11-30 08:20 UTC, Olegas approved these changes

2022-11-30 08:20 UTC, Olegas commented
Шикарно! 👍

2022-11-30 08:21 UTC, readOnlyMode commented on packages/client/src/pages/Error/styles.module.scss
> +  & .code {
Спасибо! Поправил.

2022-11-30 08:43 UTC, merged