Task 17 page forum
alexandr-kazakov/20-businessmen-team-02 pull request #7
Opened 2022-11-29 14:50 UTC by opv1

### Какую задачу решаем
Заготовка страницы профиля

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-11-29 15:56 UTC, Olegas requested changes

2022-11-29 15:56 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumItem/index.tsx
> +interface IComponent {
Несколько странный нейминг. Выглядит будто интерфейс описывает компонент (его API?) но на самом деле это его пропсы. Предлагаю пропсы именовать %ComponentName%Props т.е. в данном случае - ForumItemProps. Или еще проще - всегда просто Props (если придерживаемся правила что в одном файле один комопнент)

2022-11-29 15:56 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumItem/styles.module.scss
> +  -webkit-line-clamp: 3;
Классная штука! 🚀

2022-11-29 15:56 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumView/index.tsx
> +        </>
Этот Fragment явно лишний. Ведь в нем всего один дочерний элемент.

2022-11-29 15:56 UTC, Olegas commented on packages/client/src/pages/Forum/redux/forumSlice.ts
> +  selectedForum: null,
**Совет на будущее**
Пока запись форума не большая, так вполне будет работать. Но если внутри потом появится много полей и, возможно, список сообщений и т.п., будет не самым лучшим решением в плане производительности складывать копию выбранного форма в это поле. 

Как вариант можно сложить его идентификатор и написать отдельный селектор, который по ид из `selectedForum` и коллекции из `listForums` может достать нужную запись

2022-11-29 17:43 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumItem/index.tsx
> +interface IComponent {
поправил

2022-11-29 17:43 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumView/index.tsx
> +        </>
поправил

2022-11-29 17:43 UTC, opv1 commented on packages/client/src/pages/Forum/redux/forumSlice.ts
> +  selectedForum: null,
поправил

2022-11-29 21:22 UTC, OlegLaskov approved these changes
По-моему, все отлично!
Есть только одно замечание, которое мне делал Олег Елифантьев:
React,FC заменить на FC, добавив {FC} в импорт из React.
Еще на глаза попался any в forumSlice.ts, но, погуглив, не нашел решения

2022-11-30 06:14 UTC, Olegas requested changes

2022-11-30 06:14 UTC, Olegas commented on packages/client/src/pages/Forum/redux/forumSlice.ts
> +      const foundedForum = state.listForums.find(forum => forum.id === payload)
Начало правильное, но пока получилось то же самое что было - мы все равно в стейте храним копию элемента из listForum.
Идея была в том, что бы в действии (setSelectedForumId) сохранить в стейт только ID форума и на этом закончить.

Второй шаг - написать селектор, который сделает тот самый поиск с 34 строки в этом файле. Примерно так:
```
const getForumState = createSelector((state) => state.forum);
const getSelectedForum = createSelector(getForumState, (forum) => forum.listForums.find(forum => forum.id === forum.selectedForumId))
```


Третий шаг - используем этот селектор там, где нам нужен выбранный форум. Это будет выглядеть как-то так:
```
const selectedForum = useSelector(getSelectedForum)
```

Доп. информация: https://redux-toolkit.js.org/api/createSelector

2022-11-30 06:14 UTC, Olegas commented on packages/client/src/pages/Forum/redux/forumSlice.ts
> +  selectedForum: null,
Если мы все сделаем правильно, в стейте не будет поля selectedForum, будет listForums и selectedForumId

2022-11-30 06:14 UTC, Olegas commented on packages/client/src/pages/Forum/components/ForumItem/index.tsx
> +    }
Тут получилось дублирование кода. Достаточно проверить `if (selectedIdForum !== forum.id)` и эта проверка нормально сработает и для случая со строки 18

2022-12-01 16:46 UTC, opv1 commented on packages/client/src/pages/Forum/redux/forumSlice.ts
> +      const foundedForum = state.listForums.find(forum => forum.id === payload)
поправил и подскажи насчет оформления этой логики, а то не уверен в ней

2022-12-01 16:47 UTC, opv1 commented on packages/client/src/pages/Forum/components/ForumItem/index.tsx
> +    }
да, перемудрил, поправил

2022-12-01 19:23 UTC, Olegas approved these changes

2022-12-01 19:38 UTC, merged